services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-net
    volumes:
      - mongo-data:/data/db

networks:
  mongo-net:
    name: mongo-net
    driver: bridge

volumes: 
  mongo-data:
